[package]
name = "truco-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.9", features = ["derive"] }
crossterm = "0.27.0"
derive_builder = "0.20.0"
owo-colors = "4.0.0"
rand = "0.8.5"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
